<a href="https://colab.research.google.com/github/duynguyen199/DiabeteLogisticRegression/blob/main/diabetes_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv("diabetes.csv")
df.head()

# xem kích thước dữ liệu
print(df.shape)
# xem tên các cột
print(df.columns)
# xem thông tin các cột
df.info()
# xem thống kê cơ bản
df.describe()

print(df["Outcome"].unique())

(768, 9)
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
[1 0]


# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

# split training and test set
X = df.drop("Outcome",axis = 1)  #lấy tất cả cột trừ cột outcome
y = df['Outcome'] # lấy cột outcome cần để tính
X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size= 0.2,
    random_state= 42,
    stratify= y  # giữ tỉ lệ 0/1 giống nhau ở train & test (quan trọng cho classification)

)

# 4) Kiểm tra kích thước
# print("X:", X.shape, "y:", y.shape)
# print("X_train:", X_train.shape, "y_train:", y_train.shape)
# print("X_test:", X_test.shape, "y_test:", y_test.shape)

# 5) Kiểm tra tỉ lệ class
# print("Overall y mean (rate of diabetic=1):", y.mean())
# print("Train y mean:", y_train.mean())
# print("Test y mean:", y_test.mean())


# tạo model
model = LogisticRegression(max_iter = 10000)

scaler = StandardScaler() # import StandardScaler để chuẩn hoá dữ liệu
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
# fit model dùng dữ liệu đã chuẩn hoá
model.fit(X_train_scaled,y_train)
import pandas as pd
# chuẩn hoá dữ liệu
X_train_scaled_df = pd.DataFrame(
    X_train_scaled,
    columns=X_train.columns
)
model.predict_proba(X_test_scaled)


# dự đoán dữ liệu
y_pred = model.predict(X_test_scaled)

# so sánh dữ liệu dự đoán với dữ liêụ thật bằng confusion matrix

print(confusion_matrix(y_test, y_pred))
print(type(X_test_scaled))
print(X_test_scaled.shape)
print(y_pred)

[[82 18]
 [26 28]]
<class 'numpy.ndarray'>
(154, 8)
[1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 1 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 0 0 0 1 0]


In [ ]:
# hạ threshold tăng recall
y_pred_03 = (model.predict_proba(X_test_scaled)[:, 1] >= 0.30).astype(int)
from sklearn.metrics import confusion_matrix, classification_report

print("Threshold = 0.50")
print(confusion_matrix(y_test, y_pred))

print("\nThreshold = 0.30")
print(confusion_matrix(y_test, y_pred_03))

print("\nReport (0.30):")
print(classification_report(y_test, y_pred_03))

Threshold = 0.50
[[82 18]
 [26 28]]

Threshold = 0.30
[[70 30]
 [10 44]]

Report (0.30):
              precision    recall  f1-score   support

           0       0.88      0.70      0.78       100
           1       0.59      0.81      0.69        54

    accuracy                           0.74       154
   macro avg       0.73      0.76      0.73       154
weighted avg       0.78      0.74      0.75       154

